### PR TITLE
Fix duplicated name bug for AddCommand

### LINKED ISSUE #62: Add sorting Cheatsheets

### LINKED ISSUE #70: Defend against multiple files with same name

### PR DESCRIPTION
**Pull request by brandontoh**

### CODE REVIEW

File: src/main/java/command/AddCommand.java [hunk 1]
```diff
@@ -20,10 +20,21 @@ public void execute() throws CommandException {
...
+        } else if (checkIfNameAlreadyExist(name)) {
+            throw new CommandException("Name already existed, please enter another name");
         }
 
         CheatSheet cheatSheet = new CheatSheet(name, programmingLanguage, description);
         CheatSheetList.add(cheatSheet);
         Printer.printAddNewCheatSheetMessage(cheatSheet);
     }
+
+    private boolean checkIfNameAlreadyExist(String name) {
```
Comment (abnermtj) [inline src/main/java/command/AddCommand.java:32]: probably can use getCheatSheet(name) instead

**Review by abnermtj — APPROVED** [review]
