### PR TITLE
Fix DataFileReaderTest, add test for text-ui

### LINKED ISSUE #55: Fix tests to pass CI test

### PR DESCRIPTION
**Pull request by adhy-p**

### CODE REVIEW

File: src/main/java/ui/UserSession.java [hunk 1]
```diff
@@ -46,6 +46,7 @@ public void runProgramSequence() {
             fileWriter.executeFunction();
         } while (!Command.isExitCommand);
 
+        ui.closeScanner();
```
Comment (abnermtj) [inline src/main/java/ui/UserSession.java:49]: big brain

**Review by abnermtj — APPROVED** [review]
looks good to me
